version: '3.7'

services:
  db:
    container_name: parking-api-db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./resources/db/migration:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: parking-api-db
    networks:
      - parking-net
  
  liquibase:
    image: liquibase/liquibase
    container_name: liquibase
    command: --url=jdbc:postgresql://parking-api-db:5432/parking-api-db --username=user --password=password --changeLogFile=changelog.xml update
    volumes:
      - ./resources/db/changelog.xml:/liquibase/changelog.xml
      - ./resources/db/migration:/liquibase/migration
    depends_on:
      - db
    networks:
      - parking-net

networks:
  parking-net:

